{{- if .Values.kong.deployment.kong.enabled }}
{{- if .Values.openshift.routes.cluster.enabled }}
{{- if .Values.kong.cluster.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kong
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}
  name: {{ .Release.Name }}-kong-cluster
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.openshift.routes.cluster.hostname | default "" | quote }}
  port:
    targetPort: "kong-cluster-tls"
  tls:
    termination: "passthrough"
  to:
    kind: Service
    name: {{ .Release.Name }}-kong-cluster
    weight: 100
  wildcardPolicy: None
{{- end -}}
{{- end -}}
{{- end -}}
