{{- if .Values.kong.deployment.kong.enabled }}
{{- if .Values.kong.enterprise.enabled }}
{{- if and .Values.kong.manager.enabled (or .Values.kong.manager.http.enabled .Values.kong.manager.tls.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kong
    app.kubernetes.io/version: '2.6'
    helm.sh/chart: kong-2.5.0
  name: {{ .Release.Name }}-kong-manager
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.routes.manager.hostname | default "" | quote }}
  port:
    targetPort: kong-manager-tls
{{ if .Values.routes.manager.tls.enabled }}
  tls:
    termination: {{ .Values.routes.manager.tls.termination | default "edge" | quote }}
{{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-kong-manager
    weight: 100
  wildcardPolicy: None
{{- end -}}
{{- end -}}
{{- end -}}
